services:
  app:
    container_name: reactdesignsystemmf
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: /app/entrypoint.sh
    environment:
      NODE_ENV: development
    tty: true
    stdin_open: true
