services:
  app:
    container_name: reactdesignsystemmf
    build: .
    volumes:
      - .:/app
    ports:
      - 5173:5173
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm run dev"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
